# Generated by Django 5.2.4 on 2025-07-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('exam_date', models.CharField(max_length=20)),
                ('exam_time', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('total_marks', models.FloatField()),
                ('bonus_marks', models.FloatField()),
                ('bonus_questions', models.TextField()),
                ('answer_key_link', models.URLField()),
            ],
        ),
    ]
